app/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('inside/', views.inside, name='berhasil'),
    path('register/', views.register, name='register'),
    path('register/process/', views.submitRegister, name='submitRegister')
]

loginsystem/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('app/', include('app.urls'))
]

app/models.py
from django.db import models

# Create your models here.

class User(models.Model):
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=20)

    def __str__(self):
        return self.username

app/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from .models import User

# Create your views here.

def index(request):
    return render(request, 'app/index.html')

def login(request):
    result = User.objects.filter(username=request.POST['username'], password = request.POST['password'])
    if len(result) >= 1:
        return HttpResponseRedirect(reverse('app:berhasil'))
    else:
        return HttpResponseRedirect(reverse('index'))

def inside(request):
    return render(request, 'app/inside.html')

def register(request):
    return render(request, 'app/register.html')

def submitRegister(request):
    new_user = User()
    new_user.username = request.POST['username']
    new_user.password = request.POST['password']
    new_user.save()
    return HttpResponseRedirect(reverse('app:index'))

loginsystem/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'welcome.html')

templates/app/index.html
{% extends 'base.html' %}

{% block title %}
Halaman Utama
{% endblock %}

{% block body %}
<div class="fs-1 text-center">Login System</div>
<form action="{% url 'app:login'  %}" method="post">
    {% csrf_token %}
    <label for="" class="form-text">Username</label>
    <input type="text" name="username" id="" class="form-control mb-2">
    <label for="" class="form-text">Password</label>
    <input type="password" name="password" id="" class="form-control mb-3">
    <input type="submit" value="Login" class="btn btn-success w-100">
</form>
{% endblock %}

templates/app/inside.html
{% extends 'base.html' %}

{% block title %}
Halaman Setelah Login
{% endblock %}

{% block body %}
<div class="fs-1 text-center">Berhasil Login</div>
{% endblock %}

templates/app/register.html
{% extends 'base.html' %}

{% block title %}
Halaman Registrasi
{% endblock %}

{% block body %}
<div class="fs-1 text-center">Registrasi</div>
<form action="{% url 'app:submitRegister'  %}" method="post">
    {% csrf_token %}
    <label for="" class="form-text">Username</label>
    <input type="text" name="username" id="" class="form-control mb-2">
    <label for="" class="form-text">Password</label>
    <input type="password" name="password" id="" class="form-control mb-3">
    <input type="submit" value="Submit" class="btn btn-success w-100">
</form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        {% block body %}
        {% endblock%}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

templates/welcome.html
{% extends 'base.html' %}

{% block title %}
Welcome
{% endblock %}

{% block body %}
<div class="text-center fs-1">Welcome to Login Apps<br><span class="fs-5"><a href="{% url 'app:index'  %}" class="btn btn-primary">Click here</a></span></div>
{% endblock %}